Замечания по диссертации и автореферату
* Автореферат
** DONE Актуальность 
   Расширить раздел до пары страниц
** DONE Цели и задачи работы
   Расширить до половины страницы, списком
** DONE Основные положения
** DONE Научная новизна и практическая ценность
   Написать заклинание про новизну результатов, добавить пару слов про практическую значимость
** DONE Структура и объем работы
   Написать общую характеристику - число страниц, глав, разделов, ссылок в списке литературы
** DONE Содержание работы
   Перенести из "Структуры и объема", расширить до трех-четырех страниц
* Замечания Владимира Дмитриевича
В целом текст стал значительно четче. 

Остались претензии к формулировкам
результатов в заключениях и (что
важнее) в положениях выносимых на
защиту. 

Эти положения хотелось бы сделать
предельно четкими -- Вам нечего
камуфлировать, работа добротная.



1. Дублирование:

стр. 4: "Аффинные алгебры Ли были открыты
Виктором Кацем [1] и Робертом Муди [2] в 1967
году в результате отказа от требования
положительной определенности матрицы
Картана, определяющего полупростые
конечномерные алгебры Ли."



стр. 5: "Изучение аффинных 

алгебр Ли было начато Виктором Кацем и
Робертом Муди в 1960-х годах 

с попытки обобщения классификации
простых конечномерных алгебр Ли на
бесконечномерный случай [1, 2]"



2. стр. 5 и стр. 4 автореферата: 

"Моделям Весса-Зумино-Новикова-Виттена
и coset-моделям посвящены 

тысячи работ. Большой интерес вызывает
и теория представлений аффинных алгебр
Ли."

Скажите четко, что имеется в виду? 

То же относится и к автореферату.



3. стр.6: 

"не максимальных" => "немаксимальных"



4. стр.6  и стр. 5 автореферата:

"Показано, что наличие расщепления
приводит к существенному упро 

щению при вычислении коэффициентов
ветвления."

Это даже не совсем так! В
действительности

" Установлена прямая связь
инъективного сплинта и ветвлений.
Доказано, что при определенных
условиях  кратности весов
вспомогательного модуля иньективного
сплинта совпадают с коэффициентами
ветвления в редукции на вложенную
подалгебру. Наличие расщепления
приводит к существенному упрощению при
вычислении коэффициентов ветвления. 

"





4. стр.6  и стр. 5 автореферата:

"Показана связь процедуры редукции с
обобщенной резольвентой"

=> 

"Исследована связь процедуры редукции
с обобщенной резольвентой"

и далее необходимо уточнить, что
достигнуто!



5. стр.6  и стр. 5 автореферата:

"Предложено обобщение стохастического
процесса..."

=> 

"Построена модель обобщенного
стохастического процесса..."



6. стр.6:

Фразу

"Алгоритм вычисления коэффициентов
ветвления реализован в пакете Affine.m для
популярной системы компьютерной
алгебры Mathematica."

переместить в первый пункт перечня
решенных задач, второй фразой.

На стр. 6 останется пояснение:
"Отметим,что пакет Affine.m может быть ..."



7. стр.6:

"Продемонстрирована роль сингулярных
элементов в описании структу 

ры модулей аффинных алгебр Ли "

Какая роль??



8. стр.6:

"Показана связь процедуры редукции с
обобщенной резольвентой Берн 

штейна-Гельфанда-Гельфанда "

Какая связь??



9. стр.7  и стр. 5 автореферата:

"Предложено обобщение..."

Слово "предложено" не годится. Может
так:

"Построена модель обобщенного
стохастического процесса
Шрамма-Лёвнера ..."



10. стр. 36:

"Широко используется альтернативный
термин представление. "

"представление" и "модуль" не являются
альтернативными понятиями.

Представление есть гомоморфизм, тогда
как модуль есть пространство
снабженное "действием".



11. стр. 44, после (1.101):

"Здесь суммирование ведется по всем
конформным семействам (то есть по 

всем представлениям алгебры a). "

До сих пор речь шла о g, и суммирование
ведется по старшим весам, а это не то,
что адекватно совокупности всех
представлений.



12. стр. 44

"Представления алгебры g можно
рассматривать как сумму представлений
подалгебры a. "

Это неясно.



13. стр. 70, 71 повторяют содержание стр.
44,45,46 (почему не сослаться).



14. стр. 71 

С частицей "не" часто возникают
проблемы, ниже всего лишь пример:

"это не возможно" => "это невозможно"

И следующая фраза как пример
непричесанности текста:

"Рассмотрим следующие пример аффинной
алгебры Ли g и аффинной 

подалгебры a: ^ ??1 →> ^ ??2 и вложение
является аффинным расширением
специального вложения ??→> ??с индексом
вложения  = 4. "



15. стр. 92

Результат недостаточно разъяснен.

"Мы показали, что разложение
сингулярного элемента, возникающее при


редукции модулей, оказывается связано
с обобщенной резольвентой Берн 

штейна-Гельфанда-Гельфанда. При этом
веер вложения порождает
параболические модули Верма.
Результаты данной главы опубликованы в
работах [18, 23]. "

Как их (результаты) можно использовать?
Что дает нам наличие, так сказать,
"параболической резольвенты"?



16. стр. 111

В заключении формулировку результата
следует уточнить: вместо

"Мы продемонстрировали, что сплинт
представляет собой очень эффек 

тивный инструмент для вычисления
коэффициентов ветвления. В частности,
..."



начать с утверждения

" Нами установлена непосредственная
связь инъективного сплинта и
ветвлений: доказано, что при условии
включения образа $phi(Phi_s^(tildemu))$ в $barC_a$
кратность веса вспомогательного
модуля определяет коэффициент
ветвления $b_nu^(mu)$. Далее мы
продемонстрировали, что это свойство
сплинта представляет очень
эффективный инструмент ..."



17. стр. 141

Слабым выглядит заключение главы 5:

"В данной главе мы использовали
свойства сингулярных элементов для 

классификации операторов изменения
граничных условий в coset-моделях 

конформной теории поля,
соответствующих стохастическим
моделям с эволюцией Шрамма-Левнера с
дополнительным блужданием на
факторпространстве .... "

Успешно ли использование указанных
свойств? Какие преимущества

выявлены?



